In [4]:
# Import packages
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Create data
data = [['Apple', 'Banana', 'Guava', 'Eggs', 'Milk', 'Steak', 'Yogurt', 'Tomatos', 'Onion', 'Nuts'],
        ['Apple', 'Banana', 'Orange', 'Eggs', 'Milk', 'Pork', 'Potatos', 'Onion', 'Choclate'],
        ['Spinach', 'Eggs', 'Milk', 'Yogurt', 'Bagel', 'Onion', 'Watermelon'],
        ['Pineapple', 'Banana', 'Eggs', 'Lemon', 'Steak', 'Broccolli', 'Onion', 'Lamb'],
        ['Apple', 'Banana', 'Beer', 'Lettuce', 'Ice cream', 'Tomatos', 'Grape', 'Strawberry']]

# One-hot encoding
te = TransactionEncoder()
data_transformed = te.fit_transform(data)
df = pd.DataFrame(data_transformed, columns=te.columns_)
df

# Find frequent item sets
frequent_items = apriori(df, min_support = 0.6, use_colnames = True)

# Generate strong association rules
rules = association_rules(frequent_items, metric ="confidence", min_threshold = 0.8)
rules = rules.sort_values(by='confidence', ascending =False)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Apple),(Banana),0.6,0.8,0.6,1.0,1.25,0.12,inf,0.5
1,(Milk),(Eggs),0.6,0.8,0.6,1.0,1.25,0.12,inf,0.5
2,(Onion),(Eggs),0.8,0.8,0.8,1.0,1.25,0.16,inf,1.0
3,(Eggs),(Onion),0.8,0.8,0.8,1.0,1.25,0.16,inf,1.0
4,(Milk),(Onion),0.6,0.8,0.6,1.0,1.25,0.12,inf,0.5
5,"(Onion, Banana)",(Eggs),0.6,0.8,0.6,1.0,1.25,0.12,inf,0.5
6,"(Banana, Eggs)",(Onion),0.6,0.8,0.6,1.0,1.25,0.12,inf,0.5
7,"(Onion, Milk)",(Eggs),0.6,0.8,0.6,1.0,1.25,0.12,inf,0.5
8,"(Milk, Eggs)",(Onion),0.6,0.8,0.6,1.0,1.25,0.12,inf,0.5
9,(Milk),"(Onion, Eggs)",0.6,0.8,0.6,1.0,1.25,0.12,inf,0.5